first commit from GitHub Moblie

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -3,7 +3,7 @@ name: Maven Build
 on:
   push:
     branches:
-      - main 
+      - main
   pull_request:
     branches:
       - main
@@ -19,26 +19,38 @@ jobs:
       - name: Set up JDK
         uses: actions/setup-java@v3
         with:
-          java-version: '17' 
+          java-version: '17'
           distribution: 'temurin'
 
       - name: Build with Maven
         run: mvn clean package
 
+      - name: Verify JAR file exists
+        id: verify_jar
+        run: |
+          JAR_PATH=$(ls target/TG2Nukkit-*.jar)
+          if [ -f "$JAR_PATH" ]; then
+            echo "JAR file found: $JAR_PATH"
+            echo "JAR_PATH=$JAR_PATH" >> $GITHUB_ENV
+          else
+            echo "JAR file not found!"
+            exit 1
+          fi
+
       - name: Upload Artifact
         uses: actions/upload-artifact@v3
         with:
           name: TG2Nukkit
-          path: target/TG2Nukkit-*.jar 
+          path: ${{ env.JAR_PATH }}
 
       - name: Create Release
-        if: github.ref == 'refs/heads/main' 
+        if: github.ref == 'refs/heads/main'
         id: create_release
         uses: actions/create-release@v1
         env:
-          GITHUB_TOKEN: ${{ secrets.PAT }} 
+          GITHUB_TOKEN: ${{ secrets.PAT }}
         with:
-          tag_name: v${{ github.run_number }} 
+          tag_name: v${{ github.run_number }}
           release_name: Release v${{ github.run_number }}
           draft: false
           prerelease: false
@@ -47,9 +59,9 @@ jobs:
         if: github.ref == 'refs/heads/main'
         uses: actions/upload-release-asset@v1
         env:
-          GITHUB_TOKEN: ${{ secrets.PAT }} 
+          GITHUB_TOKEN: ${{ secrets.PAT }}
         with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: target/TG2Nukkit-*.jar
+          asset_path: ${{ env.JAR_PATH }}
           asset_name: TG2Nukkit.jar
           asset_content_type: application/java-archive
